site_name: learning-resources
nav:
    - Home: index.md
    - Introduction to Github: github.md
    - Introduction to Conda: conda.md
    - Introduction to Numpy: numpy.md
    - Introduction to Pandas: pandas.md
    - GEE Access and Javscript Tips: gee_javascript.md
    - Project Roles and Responsibilities: project.md
    - Diversity Statement: diversityMethods.md
    - Vocabulary and Acronyms: VocabAcronyms2020.md
    - How to Contribute: howtocontribute.md
theme: 
    name: readthedocs
    highlightjs: true
plugins:
    - search
    - markdownextradata
extra:
  hackweek:
    name: Waterhackweek
    web_url: https://waterhackweek.github.io
    slack_url: https://waterhackweek.slack.com
    github_org_url: https://github.com/waterhackweek
    pangeo_url: https://aws-uswest2.pangeo.io
    cyberseminar_url: https://www.cuahsi.org/education/cyberseminars/waterhackweek-cyberseminar-series
    admin_contact: Jane Koh
markdown_extensions:
  - admonition
repo_url: https://github.com/waterhackweek/learning-resources
