site_name: ICESat-2 Hackweek Learning Resources
nav:
    - Overview: index.md
    - Conduct:
        - Code of Conduct: conduct/conduct.md
        - Learning Community: conduct/community.md
        - Virtual Etiquette: conduct/etiquette.md
    - Logistics:
        - Today's Activitites: logistics/today.md
        - Hackweek Schedule: logistics/schedule.md
        - Learning Technologies: logistics/technology.md
    - Preliminary Steps:
        - GitHub account: preliminary/github.md
        - JupyterHub connection: preliminary/jupyterhub.md
        - Python installation: preliminary/conda.md
        - Earthdata login: preliminary/earthdata.md
    - Tutorials:
        - Getting Started: tutorials/getting_started.md
        - Introduction to GitHub: tutorials/github.md
        - Introduction to Jupyter: tutorials/jupyter.md
        - Introduction to Python: tutorials/python.md
    - Projects:
        - Project Roles and Responsibilities: projects/project.md
        - Project Example Workflow and Data: projects/example_workflow.md
    - Reference:
        - Vocabulary and Acronyms: reference/VocabAcronyms.md
    - About:
        - How to Contribute: about/howtocontribute.md
theme: 
    name: readthedocs
    collapse_by_default: false
    highlightjs: true
plugins:
    - search
    - markdownextradata
extra:
  hackweek:
    name: ICESat-2 hackweek
    web_url: https://icesat-2hackweek.github.io
    slack_url: https://icesat2hackweek.slack.com
    github_org_url: https://github.com/icesat-2hackweek
    pangeo_url: http://icesat-2.hackweek.io/
    admin_contact: Jane Koh
markdown_extensions:
  - admonition
repo_url: https://github.com/icesat-2hackweek/learning-resources

extra_css:
    - css/extra.css